<?php
// $Id$

/**
 * @file
 * Some Victoriac quick and dirty site specific customisation
 */

/**
 * Implementation of hook_menu()
 */

function victoriac_custom_menu() {
  $items['admin/settings/victoriac_custom'] = array(
      'title' => 'Victoriac Custom settings',
      'description' => 'Set Victoriac Custom variables.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('victoriac_custom_admin_settings'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'victoriac_custom.admin.inc',
    );
    
    return $items;
}

 /**
 * Implementation of hook_nodeapi()
 *
 * Add wrapper around body field
 * See http://capellic.com/blog/theming-the-node-body-field
 */
function victoriac_custom_nodeapi(&$node, $op, $teaser, $page) {
  // Add wrapper class to node body field
  if ($op == 'view') {
    $node->content['body']['#value'] = "<div class=\"node-body\">" . 
      $node->content['body']['#value'] . "</div>";
  }
  
  // Always show 'read more'
  if ($op == 'view' && $teaser && ($node->type != 'today')) {
    $node->readmore = true;
  }
}

/**
 * Implementation of hook_block().
 */
function victoriac_custom_block($op = 'list', $delta = 0, $edit = array()) {

  switch ($op) {
    case 'list':
    
      $blocks[0]['info'] = t('VictoriaC greeting');
      $blocks[0]['cache'] = BLOCK_NO_CACHE;      
    
      $blocks[1]['info'] = t('VictoriaC greeting 2');
      $blocks[1]['cache'] = BLOCK_NO_CACHE;
    
      $blocks[2]['info'] = t('VictoriaC Author info');
      $blocks[2]['cache'] = BLOCK_CACHE_GLOBAL;
      
      $blocks[3]['info'] = t('VictoriaC Breadcrumb');
      $blocks[3]['cache'] = BLOCK_CACHE_PER_PAGE;
      
      $blocks[4]['info'] = t('VictoriaC Twitter block (1)');
      $blocks[4]['cache'] = BLOCK_NO_CACHE;

      $blocks[5]['info'] = t('VictoriaC Twitter block (2)');
      $blocks[5]['cache'] = BLOCK_NO_CACHE;
      
      $blocks[6]['info'] = t('VictoriaC Other Twitter block');
      $blocks[6]['cache'] = BLOCK_NO_CACHE;
          
      return $blocks;
      
    case 'configure':
    
      $form = array();
      if ($delta == 2) {
        $form['victoriac_custom_block_author_info'] = array(
          '#type' => 'textarea',
          '#title' => t('Author info'),
          '#default_value' =>  variable_get('victoriac_custom_block_author_info', 'Victoria is a web developer working in Oxford, UK. She was born and raised in Singapore.'),
          '#cols' => 60,
          '#rows' => 5,
          '#description' => t('Enter the content here in clean HTML code'),
        );
        $form['victoriac_custom_block_author_info_ja'] = array(
          '#type' => 'textarea',
          '#title' => t('Author info (Japanese)'),
          '#default_value' =>  variable_get('victoriac_custom_block_author_info_ja', 'Victoria is a web developer working in Oxford, UK. She was born and raised in Singapore.'),
          '#cols' => 60,
          '#rows' => 5,
          '#description' => t('Enter the Japanese Language content here in clean HTML code'),
        );
        $form['victoriac_custom_block_author_info_zh'] = array(
          '#type' => 'textarea',
          '#title' => t('Author info (Chinese)'),
          '#default_value' =>  variable_get('victoriac_custom_block_author_info_zh', 'Victoria is a web developer working in Oxford, UK. She was born and raised in Singapore.'),
          '#cols' => 60,
          '#rows' => 5,
          '#description' => t('Enter the Chinese Language content here in clean HTML code'),
        );
        $form['victoriac_custom_block_author_link'] = array(
          '#type' => 'textfield',
          '#title' => t('Link to author profile'),
          '#default_value' =>  variable_get('victoriac_custom_block_author_link', 'about'),
          '#size' => 30,
          '#maxlength' => 30,
          '#description' => t("Enter the link for author profile as you would use in l(), eg, 'about'"),
        );        
      } elseif ($delta == 4) {
        $form['victoriac_custom_block_twitter_title'] = array(
          '#type' => 'textfield',
          '#title' => t('Twitter block title'),
          '#default_value' =>  variable_get('victoriac_custom_block_twitter_title', 'On Twitter...'),
          '#size' => 30,
          '#maxlength' => 100,
          '#description' => t("Enter the Twitter block title"),
        );
        $form['victoriac_custom_block_twitter_username'] = array(
          '#type' => 'textfield',
          '#title' => t('Twitter username'),
          '#default_value' =>  variable_get('victoriac_custom_block_twitter_username', '@victoriachan'),
          '#size' => 20,
          '#maxlength' => 50,
          '#description' => t("Enter the Twitter username, eg. @victoriachan"),
        );
        $form['victoriac_custom_block_twitter_num_items'] = array(
          '#type' => 'textfield',
          '#title' => t('Number of tweets to pull'),
          '#default_value' =>  variable_get('twitter_pull_num_items', 5),
          '#size' => 5,
          '#maxlength' => 5,
          '#description' => t("Enter the maximum number of tweets to show"),
        );
        $form['victoriac_custom_block_twitter_cache_length'] = array(
          '#type' => 'textfield',
          '#title' => t('Duration to cache'),
          '#default_value' =>  variable_get('twitter_pull_cache_length', 20),
          '#size' => 10,
          '#maxlength' => 20,
          '#description' => t("Enter duration to cache tweets in minutes (eg. 20 = 20mins)"),
        );
        $form['victoriac_custom_block_twitter_empty_message'] = array(
          '#type' => 'textarea',
          '#title' => t('Empty text'),
          '#default_value' =>  variable_get('twitter_pull_empty_message', 'No tweets found'),
          '#cols' => 60,
          '#rows' => 2,
          '#description' => t("Enter text to show when empty"),
        );
      } elseif ($delta == 6) {
        $form['victoriac_custom_block_twitter_title_2'] = array(
          '#type' => 'textfield',
          '#title' => t('Twitter block title'),
          '#default_value' =>  variable_get('victoriac_custom_block_twitter_title_2', 'On Twitter...'),
          '#size' => 30,
          '#maxlength' => 100,
          '#description' => t("Enter the Twitter block title"),
        );    
      }
      return $form;
      
    case 'save':

      if ($delta == 2) {
        // Have Drupal save the string to the database.
        variable_set('victoriac_custom_block_author_info', $edit['victoriac_custom_block_author_info']);
        variable_set('victoriac_custom_block_author_info_ja', $edit['victoriac_custom_block_author_info_ja']);
        variable_set('victoriac_custom_block_author_info_zh', $edit['victoriac_custom_block_author_info_zh']);
        variable_set('victoriac_custom_block_author_link', $edit['victoriac_custom_block_author_link']);
      } elseif ($delta == 4) {
        variable_set('victoriac_custom_block_twitter_title', $edit['victoriac_custom_block_twitter_title']);
        variable_set('victoriac_custom_block_twitter_username', $edit['victoriac_custom_block_twitter_username']);
        variable_set('twitter_pull_num_items', $edit['victoriac_custom_block_twitter_num_items']);
        variable_set('twitter_pull_cache_length', $edit['victoriac_custom_block_twitter_cache_length']);
        variable_set('twitter_pull_empty_message', $edit['victoriac_custom_block_twitter_empty_message']);
      } elseif ($delta == 6) {
        variable_set('victoriac_custom_block_twitter_title_2', $edit['victoriac_custom_block_twitter_title_2']);
      }
      return;
      
    case 'view': default:
    
      switch ($delta) {
        case 0:
          // The subject is displayed at the top of the block. Note that it
          // should be passed through t() for translation.
          $block['content'] = victoriac_custom_user_greeting_block_content();
          break;
        case 1:
          $block['content'] = victoriac_custom_user_greeting_block_content();
          break;
        case 2:
          $block['content'] = victoriac_custom_author_info_block_content();
          break;
        case 3:
          $block['content'] = victoriac_custom_breadcrumb_block_content();
          break; 
        case 4:
          $block['content'] = victoriac_custom_twitter_block_content();
          break;
        case 5:
          $block['content'] = victoriac_custom_twitter_block_content();
          break; 
        case 6:
          $block['content'] = victoriac_custom_twitter_others_block_content();
          break;                                 
      }
      return $block;
  }
}

function victoriac_custom_user_greeting_block_content () {
  global $user;
  $output = "";
  if ($user->uid) {
    $output .= "<li>".l(t('Hello,').' '.$user->name, 'user/' . $user->uid)."</li>";
    $output .= '<li class="divider">★</li>';
    $output .= "<li>".l(t('Log out'), 'logout')."</li>";
  } else {
    $output .= "<li>".l(t('Tell me who you are'), 'user/register')."</li>";
    $output .= '<li class="divider">★</li>';
    $output .= "<li>".l(t('Log in'), 'user/login')."</li>";
  }

  $output = '<ul class="user_greeting">'.$output.'</ul>';
  return $output;
}

function victoriac_custom_breadcrumb_block_content () {
  $breadcrumb = drupal_get_breadcrumb();
  if ($breadcrumb) {
    return theme_breadcrumb($breadcrumb);
  } else {
    return '';
  }
}

function victoriac_custom_author_info_block_content () {
  
  // Get content for the active lang
  
  global $language ;
  $lang_name = $language->language ;
  if ($lang_name == 'ja') {
    $form_content = variable_get('victoriac_custom_block_author_info_ja','');
  } elseif ($lang_name == 'zh-hans') {
    $form_content = variable_get('victoriac_custom_block_author_info_zh','');
  } else {
    $form_content = variable_get('victoriac_custom_block_author_info','');
  }

  // Get site author
  $site_author = user_load(variable_get('victoriac_custom_site_author_id','1'));
  if ($site_author) {  
    // calling function in template.php, not sure how else to do this
    $site_author_avatar = _leggy_make_avatar_thumb($site_author->name, $site_author->picture);  
    $link_to = variable_get('victoriac_custom_block_author_link','');
    
    $output = $site_author_avatar;
    $output .= '<p class="content_text">'.t($form_content).'</p>';
    $output .= '<p class="more_link">'.l(t('More about Victoria').' »', $link_to).'</p>';
    $output = '<div id="author_info">'.$output.'</div>';
    return $output;
  } else {
    return 'Author not found';
  }
}

function victoriac_custom_twitter_block_content () {
  module_load_include('module', 'twitter_pull', 'twitter_pull');
  $twitter_username = variable_get('victoriac_custom_block_twitter_username','');
  $twitter_block_title = variable_get('victoriac_custom_block_twitter_title','');
  return twitter_pull_render($twitter_username, $twitter_block_title);
}

function victoriac_custom_twitter_others_block_content () {
  module_load_include('module', 'twitter_pull', 'twitter_pull');
  $twitter_username = variable_get('victoriac_custom_block_twitter_username','');
  $twitter_block_title = variable_get('victoriac_custom_block_twitter_title_2','');
  return twitter_pull_render('#'.$twitter_username, $twitter_block_title, 5);
}